### ISSUE TITLE
clear adapter call history

### ISSUE THREAD

**Issue by GusRodrigues86** [lomsa-dev/http-mock-adapter#77]
Provide a way to clear previous call from adapter history to be called on every tearDown during tests.

**Comment by GiorgiBeriashvili** [comment]
Makes sense. I will try to implement a solution.

Thank you for the issue!

**Comment by kuhnroyal** [comment]
This may be solved by https://github.com/lomsa-dev/http-mock-adapter/pull/82 - it is not really a way to clear but without the static instance you can just create a new adapter.

**Comment by GiorgiBeriashvili** [comment]
#82 does indeed solve it in one way.

I also attempted to add a user-friendly method in order to reset history in #85 after each test call as shown here:

```dart
tearDown(() => dioAdapter.history.reset());
```

@GusRodrigues86 Please let me know if either of the solutions is enough for your use case.

There is also `history.data` public property which is a `List` type that holds the mocked data in history, and may prove to be useful if one requires more granular control over the tests, such as removing the last item or editing an item or so forth.

**Comment by GusRodrigues86** [comment]
The call to reset makes more sense on the context of the setUp -> tearDown approach of tests

**Comment by GiorgiBeriashvili** [comment]
Closing the issue due to the merging of #85
